name: EnvySynapseTool
main: dev.anullihate.est.Main
version: ${pom.version}
api: ["1.0.0"]
author: anullihate

depend:
  - "SynapseAPI"
loadbefore:
  - "TransferCommand"

commands:
  transfer:
    description: Switch server
    usage: "/transfer <target>"
    aliases: ["srv"]
    permission: synapse.commands.transfer
  hub:
    description: Go to lobby server
    usage: "/hub"
    permission: synapse.commands.hub

permissions:
  synapse.commands.transfer:
    description: "synapse.commands.transfer"
    default: true
  synapse.commands.hub:
    description: "synapse.commands.hub"
    default: true